server:
  port: '8088'

spring:
  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    url: 'jdbc:h2:mem:petsDb'
    driverClassName: org.h2.Driver
    username: sa

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

  cache:
    jcache:
      config: 'classpath:ehcache.xml'
